baseURL = "https://lukebrewerton.com/"
languageCode = "en-us"
title = "Luke Brewerton"
theme = "hugo-resume"
enableGitInfo = true

[params]
    firstName = "Luke"
    lastName = "Brewerton"
    address = "Brighton, UK"
    phone = ""
    contactNote = "Infrastructure/DevOps Engineer"
    profileImage = "img/profile_image.jpg"
    email = "luke@brewerton.me"
    description = "Infrastructure/DevOps Engineer with experience leveraging Docker, Kubernetes and Ansible along with coding in NodeJS, Python and Go to provide a DevOps environment"
    favicon = "img/favicon.ico"
    # Sections
    showSkills = true
    showProjects = true
    showOpenSource = true
    showPublications = false
    showExperience = true
    showEducation = true

    #Misc Settings
    showQr = true
    gitCommitPrefix = "https://github.com/lukebrewerton/portfolio/commit"

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/lukebrewerton/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/lukebrewerton/"

[[params.handles]]
    name = "Stack Overflow"
    link = "https://stackoverflow.com/users/story/4085041"
    icon = "stack-overflow"

[params.google.analytics]
    trackerID = "UA-119812227-1"
